server.port: 8083

spring:
  application:
    name: product-catalog
  mongodb:
    uri: mongodb://root:algashop@localhost:27017/product_catalog?authSource=admin
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG
    org.mongodb.driver.connection: DEBUG

algashop:
  data-load:
    enabled: true
    auto-delete: true
    sources:
      - location: db/testdata/categories.json
        collection: categories
      - location: db/testdata/products.json
        collection: products